CBV_django_test/urls.py
from django.contrib import (admin)
from django.urls import (path, include)
from django.conf.urls.static import (static)
from django.conf import (settings)

urlpatterns = [
    path(
        'admin/', admin.site.urls
        ),
    path(
        'CBV-teste-app/', include('CBV_teste_app.urls')
        ),
    path(
        '', include('exemplo.urls')
        ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls")),]

CBV_teste_app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from CBV_teste_app.views import TempView, ProdutosList



urlpatterns = [
    path(
        'template_view/', 
        TemplateView.as_view(template_name='CBV_teste_app/template_view.html'), 
        name='template-view'),
    path(
        'tempview/', TempView.as_view(), name='temp-view'
        ),
    path(
        'cbv/', ProdutosList.as_view(), name='cbv'
    ),
]

exemplo/urls.py
from django.urls import path
from exemplo import views

app_name = 'exemplo'
urlpatterns = [
    path(
        'index', 
        views.ClienteList.as_view(), 
        name='list'
    ),
    path(
        '', 
        views.ClienteCreate.as_view(), 
        name='create'
    ),
    path(
        'update/<int:pk>/', 
        views.ClienteUpdate.as_view(), 
        name='update'
    ),
    path(
        'detail/<int:pk>/', 
        views.ClienteDetail.as_view(), 
        name='detail'
    ),
    path(
        'delete/<int:pk>/',
        views.ClienteDelete.as_view(),
        name='delete'
    ),
]

CBV_teste_app/models.py
from django.db import models

# Create your models here.


class Produtos(models.Model):
    
    nome = models.CharField(max_length=50)
    preço = models.FloatField()

    def __str__(self) -> str:
        return self.nome

exemplo/models.py
from django.db import models

# Create your models here.

class Cliente(models.Model):
    nome = models.CharField(max_length=30)
    idade = models.IntegerField(blank=True, null=True)
    cpf = models.CharField()
    numero_da_conta = models.IntegerField()
    agencia = models.IntegerField()
    senha = models.CharField(max_length=8)
    email = models.CharField(max_length=254)
    senha_email = models.CharField(max_length=8)

    def __str__(self) -> str:
        return self.nome

exemplo/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.Form):
    class Meta:
        model = Cliente
        fields = '__all__'

CBV_teste_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, View
from .models import Produtos
# Create your views here.


class TempView(TemplateView):
    template_name = 'CBV_teste_app/temp_view.html'

class ProdutosList(ListView):
    model = Produtos
    queryset = Produtos.objects.all()

exemplo/views.py
from django.shortcuts import (
    render, redirect
)
from django.urls import reverse_lazy
from django.views.generic import (
    ListView, CreateView, UpdateView, DetailView, DeleteView, View
)
from exemplo.models import Cliente

# Create your views here.

#procura numa pasta com nome da app um arquivo com nome modelo + _list.html no caso seria cliente_list.html
class ClienteList(ListView):
    model = Cliente
    paginate_by = 1
    queryset = Cliente.objects.all()

#procura numa pasta com nome da app um arquivo com nome modelo + _form.html no caso seria cliente_form.html
class ClienteCreate(CreateView):
    model = Cliente
    fields = '__all__'
    success_url = reverse_lazy('exemplo:list')

#usa o mesmo html de ClienteCreate pois todos os valores são iguais
class ClienteUpdate(UpdateView):
    model = Cliente
    fields = '__all__'
    success_url = reverse_lazy('exemplo:list')

#procura numa pasta com nome da app um arquivo com nome modelo + _detail.html no caso seria cliente_detail.html
class ClienteDetail(DetailView):
    queryset = Cliente.objects.all()


class ClienteDelete(DeleteView):
    queryset = Cliente.objects.all()
    success_url = reverse_lazy('exemplo:list')

class MyView(View):
    
    def post(self, request):
        return redirect("exemplo list")

CBV_teste_app/templates/CBV_teste_app/produtos_list.html
{% extends 'base.html' %}
 
{% block title %}Produtos lista{% endblock %}


{% block body %}

    <h1>Lista:</h1>
    <br>
    {% for produto in object_list %}
        {{produto}}
        <hr>
    {% endfor %}
    
{% endblock %}

CBV_teste_app/templates/CBV_teste_app/temp_view.html
{% extends 'base.html' %}

{% block title %} template_view {% endblock %}


{% block body %}

temp_view

{% endblock %}

CBV_teste_app/templates/CBV_teste_app/template_view.html
{% extends 'base.html' %}

{% block title %} template_view {% endblock %}


{% block body %}

template_view

{% endblock %}

exemplo/templates/exemplo/cliente_confirm_delete.html
{% extends 'base.html' %}
 
{% block title %}delete {{object}}{% endblock %}


{% block body %}
    tem certeza que deseja apagar o cliente '{{object.name}}'
    {% url 'exemplo:list' as exemplo_list %}
    
    <form action="" method="post">{% csrf_token %}
        <input type="submit" value="apagar">
        <input type="reset" onclick="location.href = '{{exemplo_list}}'" value="não apagar">
    </form>
{% endblock %}

exemplo/templates/exemplo/cliente_detail.html
{% extends 'base.html' %}
 
{% block title %}{{cliente}}{% endblock %}


{% block body %}
    {% url 'exemplo:list' as exemplo_list %}
    <input type="submit" onclick="location.href = '{{exemplo_list}}'" value="Voltar para a lista">
    <br>
    nome: {{object.nome}}
    <br>
    idade {{object.idade}}

{% endblock %}

exemplo/templates/exemplo/cliente_form.html
{% extends 'base.html' %}
 
{% block title %}Criar Cliente{% endblock %}


{% block body %}

    <h1>
        Cadastro de clinte
    </h1>
    <form method="post" action="">{% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Criar">
        {% url 'exemplo:list' as exemplo_list_url %}
        <input type="reset" value="Cancelar" onclick="location.href = '{{exemplo_list_url}}'">
    </form>

{% endblock %}

exemplo/templates/exemplo/cliente_list.html
{% extends 'base.html' %}
 
{% block title %}Lista de Clientes{% endblock %}


{% block body %}
    
    <h1>Lista:</h1>
    {% url 'exemplo:create' as exemplo_create_url %}
    <input type="submit" value="Criar cliente" onclick="location.href = '{{exemplo_create_url}}'">
    <ul>
        {% for cliente in object_list %}
        <li>
            {{cliente}} - <a href="{% url 'exemplo:update' cliente.id %}">Editar</a> - 
            <a href="{% url 'exemplo:detail' cliente.id %}">Detail</a> - 
            <a href="{% url 'exemplo:delete' cliente.id %}">Delete</a>
        </li>
        <hr>
        {% endfor %}   
    </ul>
    
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock head %}
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>